DOMAIN = "elterm_proxy"
DEFAULT_NAME = "elterm"
DEFAULT_LISTEN_PORT = 9999
DEFAULT_FORWARD_HOST = "46.242.129.11"
DEFAULT_FORWARD_PORT = 88
DEFAULT_DEV_ID = "XXXX"
DEFAULT_DEV_PIN = "XXXX"
ATTR_MANUFACTURER = "Elterm"