set_elterm_parameters:
  name: Elterm parameters to set
  description: 
  fields:
    SetBoilerTempCmd:
      name: Temperature
      description: Boiler set temperature
      required: false
      selector:
        number:
          min: 20
          max: 70
          step: 1
    SetBuModulMax:
      name: Power
      description: Boiler set power
      required: false
      selector:
        number:
          min: 0
          max: 2